spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver   #mysql-connector-java 6以上不再使用com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/basemanager?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8   #时区东八区
    username: root
    password: root

mybatis-plus:
  # config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*Mapper.xml  #指定mapper.xml的位置
  # type-aliases-package: com.company.basemanager.entity
  global-config:
    db-config:
      id-type: none  # 主键策略全局配置:默认雪花算法，自动生成长度为20位的int类型

logging:
  level:
    root: warn
    com.company.basemanager.dao: trace  # mybatis-plus很多日志都是这个级别
  pattern:
    console: '%p%m%n' #p:级别 m:内容 n:换行

